services:
  redacted-bot:
    container_name: "redacted-bot"
    restart: "unless-stopped"
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/home/node/redacted-bot/data
